import { describe, expect, test } from "vitest";
import {
  addDays,
  checkNotFuture,
  DateParseError,
  FutureDateError,
  formatIso,
  fromDayNumber,
  isValidDate,
  parseDate,
  parseIso,
  pyStrip,
  toDayNumber,
  weekday,
} from "../src/index";
import { readJson } from "./support";

interface Oracle {
  today: string;
  accept: { input: string; kind: string; anchor: string }[];
  reject: string[];
}

const oracle = readJson<Oracle>("dates.json");
const today = parseIso(oracle.today);

describe("date oracle (test-vectors/dates.json, generated by parse_period)", () => {
  test("oracle is non-trivial", () => {
    expect(oracle.accept.length).toBeGreaterThan(40);
    expect(oracle.reject.length).toBeGreaterThan(40);
  });

  test.each(oracle.accept.map((a) => [JSON.stringify(a.input), a] as const))(
    "accepts %s",
    (_label, item) => {
      const period = parseDate(item.input, today);
      expect(period.kind).toBe(item.kind);
      expect(formatIso(period.anchor)).toBe(item.anchor);
    },
  );

  test.each(oracle.reject.map((r) => [JSON.stringify(r), r] as const))(
    "rejects %s",
    (_label, text) => {
      expect(() => parseDate(text, today)).toThrow(DateParseError);
    },
  );
});

describe("FR2 forms", () => {
  const cases: [string, string, string][] = [
    ["2024", "year", "2024-01-01"],
    ["2024-06", "month", "2024-06-01"],
    ["06/2024", "month", "2024-06-01"],
    ["2024/06", "month", "2024-06-01"],
    ["Jun 2024", "month", "2024-06-01"],
    ["June 2024", "month", "2024-06-01"],
    ["2024-06-03", "day", "2024-06-03"],
    ["06/03/2024", "day", "2024-06-03"],
    ["3 June 2024", "day", "2024-06-03"],
    ["3 Jun 2024", "day", "2024-06-03"],
    ["June 3, 2024", "day", "2024-06-03"],
    ["Jun 3, 2024", "day", "2024-06-03"],
    ["0001", "year", "0001-01-01"],
    ["0999-12-31", "day", "0999-12-31"],
    ["2024-02-29", "day", "2024-02-29"],
  ];
  test.each(cases)("%s", (text, kind, anchor) => {
    const period = parseDate(text, today);
    expect([period.kind, formatIso(period.anchor)]).toEqual([kind, anchor]);
  });

  test("keywords resolve to the supplied today", () => {
    for (const word of ["today", "now", "latest", "TODAY", " Now "]) {
      expect(parseDate(word, parseIso("2001-02-03"))).toEqual({
        kind: "day",
        anchor: { year: 2001, month: 2, day: 3 },
      });
    }
  });

  test("Python whitespace rules: strip removes U+001C..U+001F and U+00A0 but not U+FEFF", () => {
    expect(parseDate("\u001c2024\u001f", today).kind).toBe("year");
    expect(parseDate("\u00a02024\u00a0", today).kind).toBe("year");
    expect(() => parseDate("\ufeff2024", today)).toThrow(DateParseError);
    expect(pyStrip("\u001c x \u0085")).toBe("x");
  });

  test("unpadded day accepts the strptime ' d' alternative only inside the pattern", () => {
    expect(formatIso(parseDate("June  3, 2024", today).anchor)).toBe("2024-06-03");
    expect(() => parseDate("June 3,2024", today)).toThrow(DateParseError);
    expect(() => parseDate("2024-13", today)).toThrow(DateParseError);
    expect(() => parseDate("2024-02-30", today)).toThrow(DateParseError);
    expect(() => parseDate("2023-02-29", today)).toThrow(DateParseError);
  });
});

describe("FR2a future rule", () => {
  test("period start after today is an error", () => {
    const t = parseIso("2026-09-29");
    for (const ok of ["2026-09-29", "2026-09", "2026", "today"]) {
      const p = parseDate(ok, t);
      expect(() => checkNotFuture(p.anchor, ok, t)).not.toThrow();
    }
    for (const bad of ["2026-09-30", "2026-10", "2027", "10/01/2026"]) {
      const p = parseDate(bad, t);
      expect(() => checkNotFuture(p.anchor, bad, t)).toThrow(FutureDateError);
      expect(() => checkNotFuture(p.anchor, bad, t)).toThrow("date is in the future");
    }
  });
});

describe("calendar arithmetic", () => {
  test("day numbers round trip across the whole range", () => {
    for (
      let n = toDayNumber(parseIso("0001-01-01"));
      n <= toDayNumber(parseIso("9999-12-31"));
      n += 997
    ) {
      expect(toDayNumber(fromDayNumber(n))).toBe(n);
    }
    expect(toDayNumber(parseIso("1970-01-01"))).toBe(0);
    expect(formatIso(fromDayNumber(-719162))).toBe("0001-01-01");
  });

  test("weekday matches known dates (Monday = 0)", () => {
    expect(weekday(parseIso("2026-09-29"))).toBe(1);
    expect(weekday(parseIso("2024-06-01"))).toBe(5);
    expect(weekday(parseIso("2024-06-02"))).toBe(6);
    expect(weekday(parseIso("1968-03-15"))).toBe(4);
  });

  test("addDays crosses months, years and leap days", () => {
    expect(formatIso(addDays(parseIso("2024-03-01"), -1))).toBe("2024-02-29");
    expect(formatIso(addDays(parseIso("2023-03-01"), -1))).toBe("2023-02-28");
    expect(formatIso(addDays(parseIso("2024-01-01"), -1))).toBe("2023-12-31");
    expect(formatIso(addDays(parseIso("1968-04-01"), -9))).toBe("1968-03-23");
    expect(formatIso(addDays(parseIso("0001-01-10"), -9))).toBe("0001-01-01");
  });

  test("validity", () => {
    expect(isValidDate(2000, 2, 29)).toBe(true);
    expect(isValidDate(1900, 2, 29)).toBe(false);
    expect(isValidDate(0, 1, 1)).toBe(false);
    expect(isValidDate(2024, 4, 31)).toBe(false);
    expect(() => parseIso("2024-6-3")).toThrow(DateParseError);
  });
});
